import { registerSchema, loginSchema } from './auth';
import { createSpaceSchema } from './spaces';
import { createPageSchema, updatePageSchema, createCommentSchema, updateCommentSchema, rollbackVersionSchema } from './pages';
import { aiBuildSchema, aiSettingsSchema, createNotificationSchema, jiraIntegrationSchema } from './ai';
import {
  createBoardSchema, updateBoardSchema,
  createColumnSchema, updateColumnSchema, reorderColumnSchema,
  createSwimlaneSchema, updateSwimlaneSchema,
  createCardSchema, updateCardSchema,
  createLabelSchema, setCardLabelsSchema,
  setCardAssigneesSchema,
  createCustomFieldSchema, updateCustomFieldSchema, setCardCustomFieldsSchema,
  createChecklistSchema, updateChecklistSchema,
  createChecklistItemSchema, updateChecklistItemSchema,
  createCardCommentSchema, updateCardCommentSchema,
  addReactionSchema,
  createCardRelationSchema,
  createCardTemplateSchema,
} from './boards';
import { createOrUpdateAiConfigSchema } from './admin';

export {
  registerSchema,
  loginSchema,
  createSpaceSchema,
  createPageSchema,
  updatePageSchema,
  createCommentSchema,
  updateCommentSchema,
  rollbackVersionSchema,
  aiBuildSchema,
  aiSettingsSchema,
  createNotificationSchema,
  jiraIntegrationSchema,
  createBoardSchema,
  updateBoardSchema,
  createColumnSchema,
  updateColumnSchema,
  reorderColumnSchema,
  createSwimlaneSchema,
  updateSwimlaneSchema,
  createCardSchema,
  updateCardSchema,
  createLabelSchema,
  setCardLabelsSchema,
  setCardAssigneesSchema,
  createCustomFieldSchema,
  updateCustomFieldSchema,
  setCardCustomFieldsSchema,
  createChecklistSchema,
  updateChecklistSchema,
  createChecklistItemSchema,
  updateChecklistItemSchema,
  createCardCommentSchema,
  updateCardCommentSchema,
  addReactionSchema,
  createCardRelationSchema,
  createCardTemplateSchema,
  createOrUpdateAiConfigSchema,
};
