"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createOrUpdateAiConfigSchema = exports.createCardTemplateSchema = exports.createCardRelationSchema = exports.addReactionSchema = exports.updateCardCommentSchema = exports.createCardCommentSchema = exports.updateChecklistItemSchema = exports.createChecklistItemSchema = exports.updateChecklistSchema = exports.createChecklistSchema = exports.setCardCustomFieldsSchema = exports.updateCustomFieldSchema = exports.createCustomFieldSchema = exports.setCardAssigneesSchema = exports.setCardLabelsSchema = exports.createLabelSchema = exports.updateCardSchema = exports.createCardSchema = exports.updateSwimlaneSchema = exports.createSwimlaneSchema = exports.reorderColumnSchema = exports.updateColumnSchema = exports.createColumnSchema = exports.updateBoardSchema = exports.createBoardSchema = exports.jiraIntegrationSchema = exports.createNotificationSchema = exports.aiSettingsSchema = exports.aiBuildSchema = exports.rollbackVersionSchema = exports.updateCommentSchema = exports.createCommentSchema = exports.updatePageSchema = exports.createPageSchema = exports.createSpaceSchema = exports.loginSchema = exports.registerSchema = void 0;
const auth_1 = require("./auth");
Object.defineProperty(exports, "registerSchema", { enumerable: true, get: function () { return auth_1.registerSchema; } });
Object.defineProperty(exports, "loginSchema", { enumerable: true, get: function () { return auth_1.loginSchema; } });
const spaces_1 = require("./spaces");
Object.defineProperty(exports, "createSpaceSchema", { enumerable: true, get: function () { return spaces_1.createSpaceSchema; } });
const pages_1 = require("./pages");
Object.defineProperty(exports, "createPageSchema", { enumerable: true, get: function () { return pages_1.createPageSchema; } });
Object.defineProperty(exports, "updatePageSchema", { enumerable: true, get: function () { return pages_1.updatePageSchema; } });
Object.defineProperty(exports, "createCommentSchema", { enumerable: true, get: function () { return pages_1.createCommentSchema; } });
Object.defineProperty(exports, "updateCommentSchema", { enumerable: true, get: function () { return pages_1.updateCommentSchema; } });
Object.defineProperty(exports, "rollbackVersionSchema", { enumerable: true, get: function () { return pages_1.rollbackVersionSchema; } });
const ai_1 = require("./ai");
Object.defineProperty(exports, "aiBuildSchema", { enumerable: true, get: function () { return ai_1.aiBuildSchema; } });
Object.defineProperty(exports, "aiSettingsSchema", { enumerable: true, get: function () { return ai_1.aiSettingsSchema; } });
Object.defineProperty(exports, "createNotificationSchema", { enumerable: true, get: function () { return ai_1.createNotificationSchema; } });
Object.defineProperty(exports, "jiraIntegrationSchema", { enumerable: true, get: function () { return ai_1.jiraIntegrationSchema; } });
const boards_1 = require("./boards");
Object.defineProperty(exports, "createBoardSchema", { enumerable: true, get: function () { return boards_1.createBoardSchema; } });
Object.defineProperty(exports, "updateBoardSchema", { enumerable: true, get: function () { return boards_1.updateBoardSchema; } });
Object.defineProperty(exports, "createColumnSchema", { enumerable: true, get: function () { return boards_1.createColumnSchema; } });
Object.defineProperty(exports, "updateColumnSchema", { enumerable: true, get: function () { return boards_1.updateColumnSchema; } });
Object.defineProperty(exports, "reorderColumnSchema", { enumerable: true, get: function () { return boards_1.reorderColumnSchema; } });
Object.defineProperty(exports, "createSwimlaneSchema", { enumerable: true, get: function () { return boards_1.createSwimlaneSchema; } });
Object.defineProperty(exports, "updateSwimlaneSchema", { enumerable: true, get: function () { return boards_1.updateSwimlaneSchema; } });
Object.defineProperty(exports, "createCardSchema", { enumerable: true, get: function () { return boards_1.createCardSchema; } });
Object.defineProperty(exports, "updateCardSchema", { enumerable: true, get: function () { return boards_1.updateCardSchema; } });
Object.defineProperty(exports, "createLabelSchema", { enumerable: true, get: function () { return boards_1.createLabelSchema; } });
Object.defineProperty(exports, "setCardLabelsSchema", { enumerable: true, get: function () { return boards_1.setCardLabelsSchema; } });
Object.defineProperty(exports, "setCardAssigneesSchema", { enumerable: true, get: function () { return boards_1.setCardAssigneesSchema; } });
Object.defineProperty(exports, "createCustomFieldSchema", { enumerable: true, get: function () { return boards_1.createCustomFieldSchema; } });
Object.defineProperty(exports, "updateCustomFieldSchema", { enumerable: true, get: function () { return boards_1.updateCustomFieldSchema; } });
Object.defineProperty(exports, "setCardCustomFieldsSchema", { enumerable: true, get: function () { return boards_1.setCardCustomFieldsSchema; } });
Object.defineProperty(exports, "createChecklistSchema", { enumerable: true, get: function () { return boards_1.createChecklistSchema; } });
Object.defineProperty(exports, "updateChecklistSchema", { enumerable: true, get: function () { return boards_1.updateChecklistSchema; } });
Object.defineProperty(exports, "createChecklistItemSchema", { enumerable: true, get: function () { return boards_1.createChecklistItemSchema; } });
Object.defineProperty(exports, "updateChecklistItemSchema", { enumerable: true, get: function () { return boards_1.updateChecklistItemSchema; } });
Object.defineProperty(exports, "createCardCommentSchema", { enumerable: true, get: function () { return boards_1.createCardCommentSchema; } });
Object.defineProperty(exports, "updateCardCommentSchema", { enumerable: true, get: function () { return boards_1.updateCardCommentSchema; } });
Object.defineProperty(exports, "addReactionSchema", { enumerable: true, get: function () { return boards_1.addReactionSchema; } });
Object.defineProperty(exports, "createCardRelationSchema", { enumerable: true, get: function () { return boards_1.createCardRelationSchema; } });
Object.defineProperty(exports, "createCardTemplateSchema", { enumerable: true, get: function () { return boards_1.createCardTemplateSchema; } });
const admin_1 = require("./admin");
Object.defineProperty(exports, "createOrUpdateAiConfigSchema", { enumerable: true, get: function () { return admin_1.createOrUpdateAiConfigSchema; } });
//# sourceMappingURL=index.js.map